#!/usr/bin/env node
'use strict'

// Make sure all the necessary node modules are installed.
const modules = require('babel-features').options().plugins
  .filter(x => {
    if (x === 'transform-regenerator') return false
    return true
  })
  .map(name => 'babel-plugin-' + name.toLowerCase())

require('child_process').execSync('npm i --save ' + modules.join(' '))
